# Configuration service that uses a git-based repository to read the files
server:
  port: 8888
spring:
  cloud:
    config:
      discovery:
        enabled: true # Flag to indicate that config server discovery is enabled (config server URL  will be looked up via discovery).
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/cyberalexander/eagle-eye.git
          searchPaths: ea-licensing-service,ea-organisation-service
          default-label: master


####
# Classpath and file-based solution
####
#server:
#   port: 8888
#spring:
#  profiles:
#    active: native
#  cloud:
#     config:
#       server:
#           native:
#              searchLocations: file://<chapter 3>/confsvr/src/main/resources/config/licensingservice,
#                               file://<chapter 3>confsvr/src/main/resources/config/organizationservice
##              #searchLocations: classpath:config/,classpath:config/licensingservice