# Configuration service that uses a git-based repository to read the files
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/cyberalexander/eagle-eye.git
          searchPaths: ea-licensing-service,ea-organisation-service
          default-label: master

encrypt:
  key: APODNU3093r2rbjzxcn09u213asdhy08WRFH # the key is used by config server to encrypt/decrypt sensitive data

management:
  endpoints:
    web.exposure:
      include: refresh


####
# Classpath and file-based solution
####
#server:
#   port: 8888
#spring:
#  profiles:
#    active: native
#  cloud:
#     config:
#       server:
#           native:
#              searchLocations: file://<chapter 3>/confsvr/src/main/resources/config/licensingservice,
#                               file://<chapter 3>confsvr/src/main/resources/config/organizationservice
##              #searchLocations: classpath:config/,classpath:config/licensingservice